### ISSUE TITLE
Enhance quote add to support adding a ChatUser's last message

### ISSUE THREAD

**Issue by jdphenix** [DevChatter/devchatterbot#113]
Enhance !quote such that a mod can use

!quote add username 

and add the user's last chat message to quotes.

**Comment by benrick** [comment]
This is a very cool idea. I've got a couple of concerns about it though. 

What happens if the user types another message before the mod types `!quote add username`? It might get the wrong message. 

This will also have the requirement that we start having the bot track and remember old messages said in chat. We're not currently doing that.

**Comment by benrick** [comment]
If we can come up with a nice way of doing something referencing previous messages, I'll bring this one back. Maybe something using whispers?

**Comment by jdphenix** [comment]
I'll probably pick this up later. "Real life" (tm) happened.
