### ISSUE TITLE
Fix Blast Help Text

### ISSUE THREAD

**Issue by benrick** [DevChatter/devchatterbot#263]
This happened to one of our viewers today.
```wheelspin: !Blast
devchatterbot: Use "!blast [choice]". Replace [choice] with one of: {choiceText}```


The `{choiceText}` should be replaced with the available options.

**Comment by jimbo8098** [comment]
I'll have a look at this

**Comment by jimbo8098** [comment]
Ok I've got the bot running and stuff but can I ask what the blast function is supposed to be doing here? I see a database table created at runtime with the name BlastTypes. When I add a new row, I'm told Id can't be blank so I'm guessing this should actually be written to through the app since it's not automatically incremented unless I'm mistaken? Should that have some kind of setting populated at initial run?
