### ISSUE TITLE
Hangman game should use a full library of words

### ISSUE THREAD

**Issue by benrick** [DevChatter/devchatterbot#69]
It's using my hard-coded collection of words right now, and should have a file or database full of them.

**Comment by TheBoboNL** [comment]
You could use a Repo to contain approved words that can be synced with a DB.
Also than viewer can suggest words that can be approved by a mod or higher.

**Comment by summer600** [comment]
I started work on this enhancement. Have the EF stuff figured out but still working on how to swap out this HardcodedWordListProvider for a list in the repository. Hope to complete this tomorrow (Thursday)

How can I create a separate pull request for this, since adding to the other one feels wrong. Should I create a branch in my local, push that o my forked repo and then create a pull request from that new branch?

**Comment by AridTag** [comment]
@summer600 Ideally you would have made a branch off of master for your first pull request and then made another branch off master for this one.

The problem you have now is your master branch is ahead of the master branch in this repo and if you do a pull request with changes for this one it will include your changes for the first pull request. Which means if for whatever reason your first pull request was denied, this new pull request would contain the changes that were rejected.

What you can do though is do `git branch <branchname> 5b065d471ec98e246e45bf8dd579233339ed6644` Which will create a new branch with whatever name you want but importantly it will create that branch from that commit id (which as of this writing is the latest commit in this repos master branch) then you can `git checkout <branchname>` and do your work.
